### ISSUE TITLE
First release

### ISSUE THREAD

**Issue by vaygr** [maquinas07/evid#3]
This is a fantastic tool, thank you!

Are there any plans to tag the first release so it's easier on packaging for different distributions?

**Comment by maquinas07** [comment]
Thanks! I've added a version flag and made a first git tag / github release. Let me know if it helps at all.

**Comment by vaygr** [comment]
Thank you, that's helpful.

I submitted the [package to AUR](https://aur.archlinux.org/packages/evid) for Arch-based distros and will maintain it from now on. Hopefully more users will discover it.

Keep up the great work!
