### ISSUE TITLE
Would be nice if we could also select a particular window to record like most screen recorders.

### ISSUE THREAD

**Issue by 103sbavert** [maquinas07/evid#7]

**Comment by maquinas07** [comment]
You can already do it, if compiling with XExtensions just click on the window. Sometimes if the cursor is dragged a pixel in any direction it detects it as an empty square, could be fixed if it's annoying enough for anyone.

**Comment by maquinas07** [comment]
Though it doesn't record the window itself but the entire area it currently occupies. If that's not enough I can check what can be done with the current approach.

**Comment by 103sbavert** [comment]
> if compiling with XExtensions just click on the window.

Not sure how that's done.



> Though it doesn't record the window itself but the entire area it currently occupies. If that's not enough I can check what can be done with the current approach.

Yeah would be nice, I was actually trying to use this app to integrate into a wrapper script which takes options like -f (fullscreen) -r (rectangular region) and -w (active window) and I give it the coordinates of the rectangular region/the window ID of the current window using slop or xdotool. Then I wanted to show a kdialog to show the saving progress using a progress bar however I have not been able to figure out how i would do this since it's something I have never done.

**Comment by maquinas07** [comment]
It's a preprocessor flag, enabled by default if you haven't touched the Makefile. 

Ffmpeg doesn't give any info of the save progress that you could use for the dialog as far as I know.

**Comment by maquinas07** [comment]
If all you want is the coordinates of the window you can extract xrectsel.c and the relevant parts of evid.c and output that to stdout. The xrectsel in this repo has that modification that allows you to extract a window's coordinates on click.

**Comment by 103sbavert** [comment]
> If all you want is the coordinates of the window you can extract xrectsel.c and the relevant parts of evid.c and output that to stdout. The xrectsel in this repo has that modification that allows you to extract a window's coordinates on click.

Nope not the window coordinates, i wanted info about how much of the saving process is finished. Well that's alright. I will figure out another way or use a different app.
